const COMMAND_SEND = "s;"
const COMMAND_BROADCAST = "b;"
const COMMAND_LIST = "ls;"
const COMMAND_QUIT = "q;"
const COMMAND_CGROUP = "cg;"
const COMMAND_BRGROUP = "bg;"
const COMMAND_JGROUP = "j;"
const COMMAND_MGROUP = "members;"
const COMMAND_LGROUP = "groups;"
const COMMAND_HMGROUP = "messages;"
const COMMAND_EGROUP = "leave;"
const COMMAND_IGROUP = "invite;"
const COMMAND_KGROUP = "kick;"
const COMMAND_BGROUP = "ban;"
const COMMAND_UGROUP = "unban;"
const COMMAND_SGROUP = "states;"
const COMMAND_DELETE = "delete;"

module.exports = {COMMAND_SEND,COMMAND_BROADCAST,COMMAND_LIST,COMMAND_QUIT,COMMAND_CGROUP,
    COMMAND_BRGROUP,COMMAND_JGROUP,COMMAND_MGROUP,COMMAND_LGROUP,COMMAND_HMGROUP,COMMAND_EGROUP,
    COMMAND_IGROUP,COMMAND_KGROUP,COMMAND_UGROUP,COMMAND_SGROUP,COMMAND_BGROUP,COMMAND_DELETE}
